restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit-advanced.py"
cluster-status: "slurm-status.py"
cluster-config: "cluster_slurm.json"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
jobs: 5000
immediate-submit: False
verbose: true
